services:
  postgres:
    ports:
      - ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    ports:
      - ${REDIS_PORT}
  
  rabbitmq:
    ports:
      - "${RABBITMQ_PORT_API}:${RABBITMQ_PORT_API}"
      - "${RABBITMQ_PORT_UI}:${RABBITMQ_PORT_UI}" # management UI
      
  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - static_volume:/app/static

  video-processor:
    volumes:
      - ./video-processor:/app

  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
      - ./frontend/dist:/app/frontend
      # - frontend_volume:/app/frontend

  frontend:
    volumes:
      - frontend_volume:/app/frontend/dist
       
  minio:
    ports:
      - "${MINIO_PORT_API}:${MINIO_PORT_API}"  # S3 API
      - "${MINIO_PORT_UI}:${MINIO_PORT_UI}"  # Web UI
    volumes:
      - minio_data:/data
