services:
  postgres:
    ports:
      - ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    ports:
      - ${REDIS_PORT}
  
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672" # management UI
      
  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles

  video-processor:
    volumes:
      - ./video-processor:/app

  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.dev.conf:ro
      - static_volume:/app/staticfiles
